### ISSUE TITLE
Working amazingly on Monterey (MSI X470 Gaming Pro Carbon)

### ISSUE THREAD

**Issue by me-abhishekpal** [donatengit/AppleIGB#9]
There were a few days when I did not realise that I have this kext to be replaced with Smalltree to be able to get to the internet. 
I have always used HoRNDIS in case my internet does not work and I was usb tethering with a phone connected to a broadband.
I just read about this, dropped in my EFI>OC>Kexts, took OC snapshot with ProperTree. Worked like a charm.
Not sure why the upload seems to be slower on CLI though.

Edit: **MSI X470 Gaming Pro Carbon**

Again, many thanks Shaneee.

![image](https://user-images.githubusercontent.com/2958671/179058805-bd3aeed2-9a35-439a-82c7-3a79bd097573.png)
![image](https://user-images.githubusercontent.com/2958671/179061271-1e628683-e5e8-44c3-a81e-56e92abd80b8.png)

**Comment by Davoleo** [comment]
Hello, strangely enough, I'm on the same MB but I'm getting quite lower download speed than when I'm on windows, just thought I'd leave it here, in case anyone else experiences the same, I still don't know the exact cause of this, but my download speed is usually above 1MB/s and to a maximum of 3MB/s while on MacOS it usually struggles to remain above 600KB/s and usually fluctuates between 50 and 200 KB/s
Which is quite bothersome since it's very slow when downloading files [via any program], but at least it works :P

**Comment by donatengit** [comment]
> while on MacOS it struggles to remain above 600KB/s and usually fluctuates between 50 and 200 KB/s

Hey @Davoleo,

Thanks for testing the driver. Did you have same issues on pre-Monterey versions of MacOS (11.x) with SmallTree driver?

**Comment by Davoleo** [comment]
Yeah, I had some kind of network issues when I used SmallTree on Catalina as well, with smalltree downloads started at a ~normal speed and then constantly decreased in speed until about 200KB/s

I've previously asked on the AMD-OSX discord, but nobody had much advice for this kind of issue other than trying AppleIGB, so I've just been putting up with it, it's not that I'm always downloading files on macOs, it can be frustrating when you have to update big dev tools like XCode, but it's not something I do everyday anyways
